version: '3.8'

services:
  passport-scanner-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - uploaded-images:/app/uploaded-images
    restart: unless-stopped

volumes:
  uploaded-images: